spring:
  application:
    name: bi-agent-4j
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bi_agent?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  ai:
    openai:
      api-key: ${CHAT_API_KEY}
      chat:
        options:
          model: qwen3-max
          temperature: 0.5
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        api-key: ${CHAT_API_KEY}
      embedding:
        options:
          model: BAAI/bge-m3
        base-url: https://api.siliconflow.cn
        api-key: ${EMBEDDING_API_KEY}
    vectorstore:
      redis:
        index-name: bi-agent-4j
        prefix: bi-agent
        initialize-schema: true
  data:
    redis:
      database: 0
      host: localhost
      port: 7379
      timeout: 5s
      connect-timeout: 5s
  mail:
    host: smtp.163.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 25
    default-encoding: UTF-8
    protocol: smtp

server:
  port: 8115

notification:
  email:
    receiver: ${NOTIFICATION_EMAIL_RECEIVER}

logging:
  level:
    root: info
  file:
    path: ./logs